INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CHANNELSELECTOR channelselector)

FIND_PATH(
    CHANNELSELECTOR_INCLUDE_DIRS
    NAMES channelselector/api.h
    HINTS $ENV{CHANNELSELECTOR_DIR}/include
        ${PC_CHANNELSELECTOR_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CHANNELSELECTOR_LIBRARIES
    NAMES gnuradio-channelselector
    HINTS $ENV{CHANNELSELECTOR_DIR}/lib
        ${PC_CHANNELSELECTOR_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CHANNELSELECTOR DEFAULT_MSG CHANNELSELECTOR_LIBRARIES CHANNELSELECTOR_INCLUDE_DIRS)
MARK_AS_ADVANCED(CHANNELSELECTOR_LIBRARIES CHANNELSELECTOR_INCLUDE_DIRS)

